### ISSUE TITLE
Support --soc_reset

### ISSUE THREAD

**Issue by psyhtest** [krai/ck-qaic#21]
Sometimes it is useful to reset the SOC before each benchmarking command to be run, for example, as part of an edge/datacenter group ("all-in-one") or in a ranging/testing power pair.

This could be implemented similar to `--sleep_before_ck_benchmark_sec` e.g.:

```
krai@rb6:~/CK/ck-qaic/script/run$ RUN_CMD_COMMON_SUFFIX="--sleep_before_ck_benchmark_sec=30" \
WORKLOADS=bert OFFLINE_ONLY=yes SUT=rb6 SDK_VER=1.8.0.137 ./run_edge.sh && date
```
just without any parameters e.g.:

```
krai@rb6:~/CK/ck-qaic/script/run$ RUN_CMD_COMMON_SUFFIX="--soc_reset" \
WORKLOADS=bert OFFLINE_ONLY=yes SUT=rb6 SDK_VER=1.8.0.137 ./run_edge.sh && date
```

Initially, the SOC reset command can be defined as:
```
SOC_RESET_CMD="echo 1 | sudo tee $(sudo find /sys/devices -name soc_reset | grep a100)"
```
(which works on all Edge appliances).

**Comment by maria-18-git** [comment]
Done.
https://github.com/krai/ck-qaic/commit/70c26ddf35f494c99afe70f0de8d3335247b999d
